### PR TITLE
Fix swarm edit and restart

### LINKED ISSUE #1094: Edit under Swarm shows same OC settings for ALL Miners
im currently running version Current Version: v2.9.0b6
theres a bug where the oc settings under -> swarm -> are the same for all miners.
For example i have miner 
[192.168.188.148](http://192.168.188.148/)
when i clock on swarm-> edit it shows 606 / 1150
if i open a new tap with http://192.168.188.148/#/settings
it shows 512 / 1150

i did some testing and found that the value of the first miner on swarm i click gets somehow saved and shown on every other miner under swarm -> edit.
So it doesnt fetch the actual value for given miner, it just shows the values retrieved for the first miner u clicked edit on swarm.
Screen from swarm->edit
Image

screen from x.x.x.148

Image

### PR DESCRIPTION
**Pull request by WantClue**
this fixes two issues on swarm 
- 1 Restart was not working (was get instead of post)
- 2 Edit Modal was not reading the values per device correctly

closes #1094

### CODE REVIEW

File: main/http_server/axe-os/src/app/components/swarm/swarm.component.ts [hunk 1]
```diff
@@ -185,13 +185,18 @@ export class SwarmComponent implements OnInit, OnDestroy {
...
+          this.toastr.success(`Bitaxe at ${axe.IP} restarted`, 'Success');
+          return of('success');
+        } else {
+          this.toastr.error(`Failed to restart device at ${axe.IP}`, 'Error');
+          return of(null);
+        }
       })
     ).subscribe(res => {
-      if (res !== null) {
+      if (res !== null && res !== 'success') {
```
Comment (duckaxe) [inline main/http_server/axe-os/src/app/components/swarm/swarm.component.ts]: It's right? If not success then success message?

Comment (WantClue) [reply main/http_server/axe-os/src/app/components/swarm/swarm.component.ts]: resolved

**Comment by ghost** [comment]
Settings page is broke with this PR

https://github.com/bitaxeorg/ESP-Miner/actions/runs/15956658378

image
